### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by Vivianstats** [bvieth/powsimR#17] opened 2018-04-15 19:42 UTC
Hello,

I got the following error while trying to install powsimR using the source package:

`ERROR: dependency ‘DECENT’  is not available for package ‘powsimR’`

I could not find DECENT either from CRAN or Bioconductor. Am I missing something here?

Thanks!

**Comment by bvieth** [comment] 2018-04-15 20:43
Hello,
DECENT is still on github. You can install it using
`require(devtools)
devtools::install_github("cz-ye/DECENT")`


Kind regards
Beate

**Comment by Vivianstats** [comment] 2018-04-15 22:56
Thanks Beate. Finally I was able to install powsimR. I was trying to reproduce the vignette example using the code:

```
TwoiLIF.params <- estimateParam(countData=kolodziejczk_cnts,
                                batchData = NULL,
                                spikeData = NULL,
                                spikeInfo = NULL,
                                Lengths = NULL,
                                MeanFragLengths = NULL,
                                Distribution = 'ZINB',
                                RNAseq = 'singlecell',
                                normalisation = 'scran',
                                sigma = 1.96,
                                NCores = NULL)
```

But I received the following error:
```
Error in scater::calculateQCMetrics(sce, nmads = 3) : 
  object must be an SCESet object.
```

Do you have any clues on this issue?

**Comment by bvieth** [comment] 2018-04-16 09:36
Dear Vivian,

unfortunately I cannot reproduce the error that you have. I have experienced some hiccups before with SIngleCellExperiment R package. I solved it by reinstalling it and its dependencies.
Did you try the manual installation description in the README file?

If possible I would try it also once with another example data set, e.g. scrbseq_gene_cnts or one of your own.

For comparison, here is my sessionInfo():

`## R version 3.4.4 (2018-03-15)
## Platform: x86_64-pc-linux-gnu (64-bit)
## Running under: Ubuntu 16.04.4 LTS
## 
## Matrix products: default
## BLAS: /usr/lib/openblas-base/libblas.so.3
## LAPACK: /usr/lib/libopenblasp-r0.2.18.so
## 
## locale:
##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
##  [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=C              
##  [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=en_US.UTF-8   
##  [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
## [11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       
## 
## attached base packages:
## [1] stats     graphics  grDevices utils     datasets  methods   base     
## 
## other attached packages:
## [1] bindrcpp_0.2.2    BiocStyle_2.6.1   powsimR_1.1.1     gamlss.dist_5.0-4
## [5] MASS_7.3-49      
## 
## loaded via a namespace (and not attached):
##   [1] genefilter_1.60.0          tximport_1.6.0            
##   [3] spam_2.1-4                 locfit_1.5-9.1            
##   [5] slam_0.1-42                ZIM_1.0.3                 
##   [7] ggthemes_3.4.2             lattice_0.20-35           
##   [9] doSNOW_1.0.16              EDASeq_2.12.0             
##  [11] stats4_3.4.4               blob_1.1.1                
##  [13] R.oo_1.21.0                withr_2.1.2               
##  [15] foreign_0.8-69             registry_0.5              
##  [17] readxl_1.0.0               matrixStats_0.53.1        
##  [19] pkgmaker_0.22              stringr_1.3.0             
##  [21] cellranger_1.1.0           munsell_0.4.3             
##  [23] SCnorm_1.0.0               DESeq2_1.18.1             
##  [25] codetools_0.2-15           SparseM_1.77              
##  [27] ADGofTest_0.3              caret_6.0-79              
##  [29] diffusionMap_1.1-0         lmtest_0.9-36             
##  [31] tclust_1.3-1               RMTstat_0.3               
##  [33] limma_3.34.9               densityClust_0.3          
##  [35] annotate_1.56.2            apcluster_1.4.5           
##  [37] brew_1.0-6                 ellipse_0.4.1             
##  [39] Rtsne_0.13                 DESeq_1.30.0              
##  [41] stringi_1.1.7              RcppRoll_0.2.2            
##  [43] qlcMatrix_0.9.5            distillery_1.0-4          
##  [45] grid_3.4.4                 sandwich_2.4-0            
##  [47] cluster_2.0.7-1            blockmodeling_0.3.0       
##  [49] pbivnorm_0.6.0             ape_5.1                   
##  [51] pkgconfig_2.0.1            pheatmap_1.0.8            
##  [53] prettyunits_1.0.2          data.table_1.10.4-3       
##  [55] lubridate_1.7.4            ggridges_0.5.0            
##  [57] energy_1.7-2               httr_1.3.1                
##  [59] igraph_1.2.1               progress_1.1.2            
##  [61] fastcluster_1.1.24         scone_1.2.0               
##  [63] modeltools_0.2-21          haven_1.1.1               
##  [65] amap_0.8-14                htmltools_0.3.6           
##  [67] miniUI_0.1.1               viridisLite_0.3.0         
##  [69] snow_0.4-2                 fastICA_1.2-1             
##  [71] yaml_2.1.18                baySeq_2.12.0             
##  [73] prodlim_1.6.1              pillar_1.2.1              
##  [75] hexbin_1.27.2              fitdistrplus_1.0-9        
##  [77] glue_1.2.0                 DBI_0.8                   
##  [79] BiocParallel_1.12.0        doRNG_1.6.6               
##  [81] plyr_1.8.4                 foreach_1.4.4             
##  [83] bindr_0.1.1                outliers_0.14             
##  [85] robustbase_0.92-8          dotCall64_0.9-5.2         
##  [87] gtable_0.2.0               pcaMethods_1.70.0         
##  [89] caTools_1.17.1             nonnest2_0.5-1            
##  [91] latticeExtra_0.6-28        Biobase_2.38.0            
##  [93] magic_1.5-8                crosstalk_1.0.0           
##  [95] AnnotationDbi_1.40.0       broom_0.4.4               
##  [97] rARPACK_0.11-0             SAVER_0.4.0               
##  [99] arm_1.10-1                 checkmate_1.8.5           
## [101] S4Vectors_0.16.0           IHW_1.6.0                 
## [103] lpsymphony_1.7.1           FNN_1.1                   
## [105] mnormt_1.5-5               png_0.1-7                 
## [107] cidr_0.1.5                 stabledist_0.7-1          
## [109] lazyeval_0.2.1             Formula_1.2-2             
## [111] crayon_1.3.4               bayesm_3.1-0.1            
## [113] RUVSeq_1.12.0              boot_1.3-20               
## [115] softImpute_1.4             xfun_0.1                  
## [117] tidyselect_0.2.4           kernlab_0.9-25            
## [119] purrr_0.2.4                splines_3.4.4             
## [121] pcaPP_1.9-73               survival_2.41-3           
## [123] penalized_0.9-50           bit64_0.9-7               
## [125] segmented_0.5-3.0          rngtools_1.2.4            
## [127] extRemes_2.0-8             scde_2.6.0                
## [129] ROTS_1.6.0                 fields_9.6                
## [131] MatrixModels_0.4-1         combinat_0.0-8            
## [133] R.methodsS3_1.7.1          SDMTools_1.1-221          
## [135] VGAM_1.0-5                 UpSetR_1.3.3              
## [137] permute_0.9-4              pscl_1.5.2                
## [139] GenomeInfoDb_1.14.0        MBESS_4.4.3               
## [141] quantreg_5.35              fdrtool_1.2.15            
## [143] htmlTable_1.11.2           BPSC_0.99.1               
## [145] trimcluster_0.1-2          xtable_1.8-2              
## [147] DT_0.4                     DelayedArray_0.4.1        
## [149] DDRTree_0.1.5              gdata_2.18.0              
## [151] ipred_0.9-6                vegan_2.5-1               
## [153] abind_1.4-5                ShortRead_1.36.1          
## [155] mime_0.5                   tensorA_0.36              
## [157] rjson_0.2.15               ggplot2_2.2.1             
## [159] RMySQL_0.10.14             ggrepel_0.7.0             
## [161] numDeriv_2016.8-1          ade4_1.7-11               
## [163] tools_3.4.4                quadprog_1.5-5            
## [165] magrittr_1.5               rgl_0.99.16               
## [167] proxy_0.4-22               tibble_1.4.2              
## [169] dynamicTreeCut_1.63-1      drc_3.0-1                 
## [171] Matrix_1.2-14              shinyBS_0.61              
## [173] DEDS_1.52.0                ggbeeswarm_0.6.0          
## [175] roxygen2_6.0.1             assertthat_0.2.0          
## [177] qvalue_2.10.0              mixtools_1.1.0            
## [179] clusterCrit_1.2.7          ica_1.0-1                 
## [181] pbapply_1.3-4              NBPSeq_0.3.0              
## [183] rtracklayer_1.38.3         mgcv_1.8-23               
## [185] R.utils_2.6.0              metap_0.8                 
## [187] BiocGenerics_0.24.0        HSMMSingleCell_0.112.0    
## [189] multcomp_1.4-8             zlibbioc_1.24.0           
## [191] commonmark_1.4             hwriter_1.3.2             
## [193] monocle_2.6.4              devtools_1.13.5           
## [195] rio_0.5.10                 biomaRt_2.34.2            
## [197] geneplotter_1.56.0         TH.data_1.0-8             
## [199] ROCR_1.0-7                 KernSmooth_2.23-15        
## [201] backports_1.1.2            scatterplot3d_0.3-41      
## [203] XVector_0.18.0             bit_1.1-12                
## [205] ggExtra_0.8                Rsamtools_1.30.0          
## [207] gplots_3.0.1               RANN_2.5.1                
## [209] ranger_0.9.0               openxlsx_4.0.17           
## [211] zingeR_0.1.0               shiny_1.0.5               
## [213] dtw_1.18-1                 GenomicRanges_1.30.3      
## [215] maps_3.3.0                 glmnet_2.0-16             
## [217] Seurat_2.3.0               viridis_0.5.1             
## [219] rstudioapi_0.7             minqa_1.2.4               
## [221] iterators_1.0.9            nlme_3.1-137              
## [223] sfsmisc_1.1-2              SummarizedExperiment_1.8.1
## [225] lavaan_0.5-23.1097         gtools_3.5.0              
## [227] beeswarm_0.2.3             RcppNumerical_0.3-2       
## [229] Rook_1.1-1                 reshape2_1.4.3            
## [231] rhdf5_2.22.0               colorspace_1.3-2          
## [233] compositions_1.40-1        base64enc_0.1-3           
## [235] GenomicFeatures_1.30.3     cobs_1.3-3                
## [237] XML_3.98-1.10              DrImpute_1.0              
## [239] ModelMetrics_1.1.0         sn_1.5-1                  
## [241] NbClust_3.0                aroma.light_3.8.0         
## [243] RColorBrewer_1.1-2         Linnorm_2.2.0             
## [245] GenomeInfoDbData_1.0.0     dimRed_0.1.0              
## [247] Biostrings_2.46.0          timeDate_3043.102         
## [249] moments_0.14               evaluate_0.10.1           
## [251] memoise_1.1.0              iCOBRA_1.6.0              
## [253] coda_0.19-1                knitr_1.20                
## [255] IRanges_2.12.0             doParallel_1.0.11         
## [257] vipor_0.4.5                httpuv_1.3.6.2            
## [259] class_7.3-14               irlba_2.3.2               
## [261] lars_1.2                   Rcpp_0.12.16              
## [263] acepack_1.4.1              formatR_1.5               
## [265] diptest_0.75-7             jsonlite_1.5              
## [267] Hmisc_4.1-1                RSpectra_0.12-0           
## [269] msir_1.3.1                 digest_0.6.15             
## [271] gmodels_2.16.2             bookdown_0.7              
## [273] dplyr_0.7.4                ddalpha_1.3.2             
## [275] CompQuadForm_1.4.3         scDD_1.2.0                
## [277] rprojroot_1.3-2            gsl_1.9-10.3              
## [279] cowplot_0.9.2              Lmoments_1.2-3            
## [281] bitops_1.0-6               RSQLite_2.1.0             
## [283] tsne_0.1-3                 EBSeq_1.18.0              
## [285] NOISeq_2.22.1              rmarkdown_1.9             
## [287] compiler_3.4.4             nnet_7.3-12               
## [289] statmod_1.4.30             RcppEigen_0.3.3.4.0       
## [291] scran_1.6.9                zoo_1.8-1                 
## [293] minpack.lm_1.2-1           carData_3.0-1             
## [295] testthat_2.0.0             geometry_0.3-6            
## [297] rlang_0.2.0                manipulateWidget_0.9.0    
## [299] nloptr_1.0.4               prabclus_2.2-6            
## [301] SingleCellExperiment_1.0.0 fpc_2.1-11                
## [303] lava_1.6.1                 pspline_1.0-18            
## [305] recipes_0.1.2              mvtnorm_1.0-7             
## [307] htmlwidgets_1.0            psych_1.8.3.3             
## [309] labeling_0.3               RcppArmadillo_0.8.400.0.0 
## [311] forcats_0.3.0              Cairo_1.5-9               
## [313] copula_0.999-18            flexmix_2.3-14            
## [315] curl_3.2                   scater_1.6.3              
## [317] parallel_3.4.4             highr_0.6                 
## [319] DEoptimR_1.0-8             edgeR_3.20.9              
## [321] scales_0.5.0               plotrix_3.7               
## [323] desc_1.1.1                 RcppParallel_4.4.0        
## [325] CVST_0.2-1                 lme4_1.1-17               
## [327] gridExtra_2.3              DECENT_0.2.0              
## [329] bbmle_1.0.20               RCurl_1.95-4.10           
## [331] ggdendro_0.1-20            DRR_0.0.3                 
## [333] car_3.0-0                  tidyr_0.8.0               
## [335] MAST_1.4.1                 xml2_1.2.0                
## [337] shinydashboard_0.7.0       gower_0.1.2               
## [339] rpart_4.1-13               R6_2.2.2                  
## [341] mclust_5.4                 zinbwave_1.0.0            
## [343] GenomicAlignments_1.14.2`

**Comment by Vivianstats** [comment] 2018-04-16 21:07
Hello Beate,

Thank you very much for your information. I reinstalled `SingleCellExperiment` and tested the two example datasets, but I got a different error this time:

```
> TwoiLIF.params <- estimateParam(countData = kolodziejczk_cnts,
+                                 batchData = NULL,
+                                 spikeData = NULL,
+                                 spikeInfo = NULL,
+                                 Lengths = NULL,
+                                 MeanFragLengths = NULL,
+                                 Distribution = 'ZINB',
+                                 RNAseq = 'singlecell',
+                                 normalisation = 'scran',
+                                 sigma = 1.96,
+                                 NCores = NULL)

Using computeSumFactors, i.e. deconvolution over all cells!
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘computeSumFactors’ for signature ‘"SingleCellExperiment"’
```
I checked the version of  `SingleCellExperiment` and we are both using 1.0.0. Any other thoughts on the reasons behind this issue? I'm also attaching my output of `sessionInfo()`.

```
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.0
LAPACK: /usr/lib/lapack/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets 
[7] methods   base     

other attached packages:
[1] powsimR_1.1.0       Biobase_2.36.2      BiocGenerics_0.22.1
[4] gamlss.dist_5.0-4   MASS_7.3-49        

loaded via a namespace (and not attached):
  [1] mixtools_1.1.0             softImpute_1.4            
  [3] minpack.lm_1.2-1           pbapply_1.3-4             
  [5] lattice_0.20-35            haven_1.1.1               
  [7] fastICA_1.2-1              mgcv_1.8-22               
  [9] penalized_0.9-50           blob_1.1.1                
 [11] survival_2.41-3            prodlim_1.6.1             
 [13] nloptr_1.0.4               DBI_0.8                   
 [15] R.utils_2.6.0              SingleCellExperiment_1.0.0
 [17] Linnorm_2.0.8              bindr_0.1.1               
 [19] zlibbioc_1.22.0            MatrixModels_0.4-1        
 [21] pspline_1.0-18             pcaMethods_1.68.0         
 [23] SDMTools_1.1-221           htmlwidgets_1.0           
 [25] mvtnorm_1.0-7              tclust_1.3-1              
 [27] scater_1.6.3               irlba_2.3.2               
 [29] DEoptimR_1.0-8             lars_1.2                  
 [31] Rcpp_0.12.16               KernSmooth_2.23-15        
 [33] DT_0.4                     gdata_2.18.0              
 [35] DDRTree_0.1.5              DelayedArray_0.2.7        
 [37] limma_3.34.9               vegan_2.5-1               
 [39] CVST_0.2-1                 RcppParallel_4.4.0        
 [41] Hmisc_4.1-1                ShortRead_1.34.2          
 [43] apcluster_1.4.5            RSpectra_0.12-0           
 [45] msir_1.3.1                 mnormt_1.5-5              
 [47] ranger_0.9.0               digest_0.6.15             
 [49] png_0.1-7                  qlcMatrix_0.9.5           
 [51] cidr_0.1.5                 cowplot_0.9.2             
 [53] glmnet_2.0-16              pkgconfig_2.0.1           
 [55] gridBase_0.4-7             gower_0.1.2               
 [57] ggbeeswarm_0.6.0           iterators_1.0.9           
 [59] minqa_1.2.4                lavaan_0.5-23.1097        
 [61] SummarizedExperiment_1.6.5 spam_2.1-4                
 [63] beeswarm_0.2.3             modeltools_0.2-21         
 [65] RcppNumerical_0.3-2        zoo_1.8-1                 
 [67] tidyselect_0.2.4           clusterCrit_1.2.7         
 [69] ZIM_1.0.3                  reshape2_1.4.3            
 [71] purrr_0.2.4                kernlab_0.9-25            
 [73] ica_1.0-1                  pcaPP_1.9-73              
 [75] EDASeq_2.10.0              viridisLite_0.3.0         
 [77] snow_0.4-2                 rtracklayer_1.36.6        
 [79] rlang_0.2.0                hexbin_1.27.2             
 [81] NbClust_3.0                glue_1.2.0                
 [83] metap_0.8                  RColorBrewer_1.1-2        
 [85] registry_0.5               fpc_2.1-11                
 [87] matrixStats_0.53.1         stringr_1.3.0             
 [89] pkgmaker_0.22              lava_1.6.1                
 [91] fields_9.6                 DESeq2_1.16.1             
 [93] recipes_0.1.2              SparseM_1.77              
 [95] httpuv_1.3.6.2             class_7.3-14              
 [97] BPSC_0.99.1                RMTstat_0.3               
 [99] annotate_1.54.0            jsonlite_1.5              
[101] XVector_0.16.0             bit_1.1-12                
[103] mime_0.5                   gridExtra_2.3             
[105] gplots_3.0.1               Rsamtools_1.28.0          
[107] zingeR_0.1.0               stringi_1.1.7             
[109] gmodels_2.16.2             RcppRoll_0.2.2            
[111] gsl_1.9-10.3               quadprog_1.5-5            
[113] bitops_1.0-6               maps_3.3.0                
[115] RSQLite_2.1.0              tidyr_0.8.0               
[117] pheatmap_1.0.8             data.table_1.10.4-3       
[119] DEDS_1.50.0                energy_1.7-2              
[121] rstudioapi_0.7             GenomicAlignments_1.12.2  
[123] sfsmisc_1.1-2              nlme_3.1-131              
[125] qvalue_2.8.0               scran_1.4.5               
[127] fastcluster_1.1.24         scone_1.0.0               
[129] locfit_1.5-9.1             miniUI_0.1.1              
[131] cobs_1.3-3                 R.oo_1.21.0               
[133] prabclus_2.2-6             segmented_0.5-3.0         
[135] readxl_1.0.0               dimRed_0.1.0              
[137] timeDate_3043.102          ROTS_1.4.0                
[139] munsell_0.4.3              cellranger_1.1.0          
[141] R.methodsS3_1.7.1          moments_0.14              
[143] hwriter_1.3.2              visNetwork_2.0.3          
[145] caTools_1.17.1             codetools_0.2-15          
[147] coda_0.19-1                magic_1.5-8               
[149] GenomeInfoDb_1.12.3        diffusionMap_1.1-0        
[151] vipor_0.4.5                lmtest_0.9-36             
[153] htmlTable_1.11.2           rARPACK_0.11-0            
[155] xtable_1.8-2               SAVER_0.4.0               
[157] ROCR_1.0-7                 diptest_0.75-7            
[159] scatterplot3d_0.3-41       lpsymphony_1.4.1          
[161] abind_1.4-5                FNN_1.1                   
[163] RANN_2.5.1                 CompQuadForm_1.4.3        
[165] GenomicRanges_1.28.6       rgl_0.96.0                
[167] tibble_1.4.2               ggdendro_0.1-20           
[169] cluster_2.0.6              Seurat_2.3.0              
[171] Matrix_1.2-14              lubridate_1.7.4           
[173] ggridges_0.5.0             NOISeq_2.20.0             
[175] shinydashboard_0.7.0       mclust_5.4                
[177] igraph_1.2.1               RcppEigen_0.3.3.4.0       
[179] slam_0.1-42                testthat_2.0.0            
[181] doSNOW_1.0.16              geometry_0.3-6            
[183] htmltools_0.3.6            NMF_0.21.0                
[185] yaml_2.1.18                GenomicFeatures_1.28.5    
[187] plotly_4.7.1               XML_3.98-1.9              
[189] ModelMetrics_1.1.0         DrImpute_1.0              
[191] foreign_0.8-69             withr_2.1.2               
[193] fitdistrplus_1.0-9         BiocParallel_1.10.1       
[195] aroma.light_3.6.0          bit64_0.9-7               
[197] rngtools_1.2.4             doRNG_1.6.6               
[199] foreach_1.4.4              robustbase_0.92-8         
[201] outliers_0.14              scde_2.4.1                
[203] Biostrings_2.44.2          combinat_0.0-8            
[205] memoise_1.1.0              VGAM_1.0-5                
[207] nonnest2_0.5-1             forcats_0.3.0             
[209] rio_0.5.10                 geneplotter_1.54.0        
[211] permute_0.9-4              caret_6.0-79              
[213] curl_3.2                   fdrtool_1.2.15            
[215] trimcluster_0.1-2          acepack_1.4.1             
[217] edgeR_3.20.9               checkmate_1.8.5           
[219] tensorA_0.36               DECENT_0.2.0              
[221] ellipse_0.4.1              ggplot2_2.2.1             
[223] rjson_0.2.15               openxlsx_4.0.17           
[225] ggrepel_0.7.0              distillery_1.0-4          
[227] ade4_1.7-11                dtw_1.18-1                
[229] scDD_1.0.0                 stabledist_0.7-1          
[231] Lmoments_1.2-3             tools_3.4.2               
[233] sandwich_2.4-0             magrittr_1.5              
[235] RCurl_1.95-4.10            proxy_0.4-22              
[237] car_3.0-0                  pbivnorm_0.6.0            
[239] ape_5.1                    bayesm_3.1-0.1            
[241] EBSeq_1.16.0               httr_1.3.1                
[243] assertthat_0.2.0           boot_1.3-20               
[245] R6_2.2.2                   nnet_7.3-12               
[247] tximport_1.4.0             genefilter_1.58.1         
[249] gtools_3.5.0               statmod_1.4.30            
[251] Rook_1.1-1                 rhdf5_2.20.0              
[253] splines_3.4.2              carData_3.0-1             
[255] colorspace_1.3-2           amap_0.8-14               
[257] stats4_3.4.2               NBPSeq_0.3.0              
[259] compositions_1.40-1        base64enc_0.1-3           
[261] baySeq_2.10.0              pillar_1.2.1              
[263] sn_1.5-1                   HSMMSingleCell_0.110.0    
[265] bindrcpp_0.2.2             GenomeInfoDbData_0.99.0   
[267] plyr_1.8.4                 extRemes_2.0-8            
[269] dotCall64_0.9-5.2          gtable_0.2.0              
[271] SCnorm_0.99.7              monocle_2.6.1             
[273] psych_1.8.3.3              knitr_1.20                
[275] RcppArmadillo_0.8.400.0.0  latticeExtra_0.6-28       
[277] biomaRt_2.32.1             IRanges_2.10.5            
[279] ADGofTest_0.3              copula_0.999-18           
[281] Cairo_1.5-9                doParallel_1.0.11         
[283] pscl_1.5.2                 flexmix_2.3-13            
[285] quantreg_5.35              AnnotationDbi_1.38.2      
[287] broom_0.4.4                scales_0.5.0              
[289] arm_1.10-1                 backports_1.1.2           
[291] IHW_1.4.0                  S4Vectors_0.14.7          
[293] densityClust_0.3           ipred_0.9-6               
[295] lme4_1.1-17                brew_1.0-6                
[297] DESeq_1.28.0               Rtsne_0.13                
[299] dplyr_0.7.4                shiny_1.0.5               
[301] ddalpha_1.3.2              grid_3.4.2                
[303] numDeriv_2016.8-1          bbmle_1.0.20              
[305] lazyeval_0.2.1             dynamicTreeCut_1.63-1     
[307] Formula_1.2-2              tsne_0.1-3                
[309] blockmodeling_0.3.0        DRR_0.0.3                 
[311] MAST_1.2.1                 RUVSeq_1.10.0             
[313] viridis_0.5.1              rpart_4.1-11              
[315] zinbwave_1.0.0             compiler_3.4.2 
```

**Comment by bvieth** [comment] 2018-06-01 10:17
Dear Vivian,

I will close the issue for now. Feel free to reopen if my suggestions did not resolve the issue for you.

Kind regards
Beate

**Closed by bvieth** 2018-06-01 10:17 UTC
